version: '3'

services:
  app:
    build: .
    ports:
      - "8080:80"

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
