services:
  react_stl_app:
    container_name: react_stl_app
    build: ./
    volumes:
      - build_react:/var/www/html

  nginx_sorteador_app:
    container_name: nginx_sorteador_app
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - build_react:/var/www/html
      - ./stl/cert:/etc/nginx/ssl
    depends_on:
      - react_stl_app

volumes:
  build_react:


